---
title: im mender? :/
description: This website is under construction.
baseurl: ""
url: "https://immender.github.io"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
collections:
  sections:
    output: true
  volumes:
    output: true
  chapters:
    output: true
sass:
    sass_dir: _sass
defaults:
  - scope:
      path: ""
      type: "sections"
    values:
      layout: "section"
  - scope:
      path: ""
      type: "volumes"
    values:
      layout: "volume"
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"
---